spring:
  application:
    name: smartmarket
  datasource:
    url: jdbc:mysql://localhost:3306/smartmarket?useSSL=false&serverTimezone=UTC
    username: root
    password: Chaara@06
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: admin123